#!/bin/bash

__DIR__=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
device=$(source $__DIR__/net-device)

line=$(LANG="C" /sbin/ifconfig $device |grep inet|grep [mM]ask)

n=0
for i in $line ; do
    if [ $n -eq 1 ] ; then ip=$i ; break ; fi
    if [[ $i = inet ]] ; then n=1 ; fi
done

echo ${ip##*:}
