#!/bin/bash

# with recent systemd eth0 is a little bit outdated.
# https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

device=eth0

if ls /sys/class/net | grep -q $device ; then true
else
    for n in $(ls /sys/class/net); do
       if [[ $n = en* ]]; then device=$n ; break ; fi
    done
fi

echo $device
